### ISSUE TITLE
News: Congrats to Chris!

### ISSUE THREAD

**Issue by bendy** [PurduePL/purduepl.github.io#105]
### DATE

2023-03-15

### Content
Huge shoutout to Christopher, Nour, and Roopsha on their recently accepted OOPSLA paper: <a href-"https://2023.splashcon.org/details/splash-2023-oopsla/7/Enabling-Bounded-Verification-of-Doubly-Unbounded-Distributed-Agreement-Based-Systems"> Enabling Bounded Verification of Doubly-Unbounded Distributed Agreement-Based Systems via Bounded Regions </a>

**Comment by Pat-Lafon** [comment]
Closed with 592184e
