### ISSUE TITLE
Seminar Talk: RTailor: Parameterizing Soft Error Resilience for Mixed-Criticality Real-Time Systems

### ISSUE THREAD

**Issue by syhuang0** [PurduePL/purduepl.github.io#134]
### Title
RTailor: Parameterizing Soft Error Resilience for Mixed-Criticality Real-Time Systems
### Abstract
Equipping real-time systems with soft error resilience can be challenging due to the tradeoff of the timing and failure requirements for mixed-criticality tasks. Violation of these requirements yields failed task scheduling in one way or another. However, not every task requires the same degree of soft error resilience. For example, low-criticality tasks can run with low or even no soft error resilience, whereas mid- or high-criticality tasks may require relatively high resilience depending on their inherent failure requirement. nfortunately, existing soft error resilience schemes do not have the ability to control the degree of their resilience in a fine grained way, i.e., they can only be turned on or off as a whole during task execution. To this end, this paper presents RTailor (Resilience Tailor), a compiler-directed parameterized soft error resilience scheme that achieves the desired level of soft error protection according to the demand of each task. The key idea is that for a given protection ratio, compilers can transform a hot loop such that the number of its iterations protected over the total iterations matches the ratio. Compared to full resilience protecting every iteration, RTailor’s parameterized soft error resilience  significantly reduces the performance overhead of tasks, thereby improving their real-time schedulability. The experimental results highlight that for four representative fault rates, RTailor achieves 15%∼21% average schedulability improvements over the state-of-the-art work that lacks parameterized soft error resilience.

**Comment by Pat-Lafon** [comment]
Do you have a bio?

**Comment by syhuang0** [comment]
Great! I will like to put it in the bio. Thanks!
