### ISSUE TITLE
Generating site locally produces empty lists of people

### ISSUE THREAD

**Issue by ulysses4ever** [PurduePL/purduepl.github.io#139]
I use docker and end up with empty lists of people. Any ideas how to fix that would be appreciated.
![2023-10-24_10-10-1698157917](https://github.com/PurduePL/purduepl.github.io/assets/6832600/a7f087be-7a20-47bf-a35f-f742f6471148)

**Comment by ulysses4ever** [comment]
As per #138, I use Jekyll 4. Maybe it breaks the way loops are setup here somehow?..

**Comment by ulysses4ever** [comment]
Weird enough, it works now...

**Comment by ulysses4ever** [comment]
I had to `rm -rf` the `_site`.

**Comment by Pat-Lafon** [comment]
Yeah, sometimes you need to full clean and restart. Sometimes it is smart enough to rebuild incrementally versus getting stuck.

**Comment by ulysses4ever** [comment]
This is worth mentioning in README under a new section, like "Tips and Tricks" or some such.
