### ISSUE TITLE
Seminar Talk: Julia: Practical Restrictions for a Scientific-Computing Language

### ISSUE THREAD

**Issue by julbinb** [PurduePL/purduepl.github.io#143]
### Title

Julia: Practical Restrictions for a Scientific-Computing Language

### Abstract

Julia is high-level, dynamic programming language for scientific computing. To achieve performance, Julia relies on an optimizing just-in-time compiler. To make compilation predictable and allow for a simpler compiler implementation, the language is intentionally designed around a few unusual restrictions. 
In the first part of the talk, we discuss “world age”—the semantics of eval function for dynamically executing code. Unlike other dynamic languages, Julia delays when eval’ed code becomes available to the rest of the program, thus allowing the compiler to retain pre-eval optimizations. A corpus analysis of Julia code shows that such delaying semantics is practical in most cases.
In the second part of the talk, we discuss a restriction on Julia’s type language that would allow for decidable subtyping. Julia’s dynamic dispatch is currently resolved with undecidable subtyping, meaning that in practice, a program can crash with a stack-overflow error due to an unfortunate subtype query. The decidability of subtyping can be recovered by restricting existential types inside invariant type constructors to use-site variance. A corpus analysis of Julia code shows that the vast majority of existing programs already adhere to this restriction.

### Bio

Julia Belyakova is a postdoctoral researcher at Purdue University, working with Suresh Jagannathan. Julia received her PhD at Northeastern University, where she worked with Jan Vitek on formalizing various aspects of the Julia language.

**Comment by Pat-Lafon** [comment]
Closed by https://github.com/PurduePL/purduepl.github.io/commit/1a306080e92342a1866ba0c040bb8f7ff8798d6b
