### ISSUE TITLE
Feature Request: add a GitHub link on the website

### ISSUE THREAD

**Issue by ulysses4ever** [PurduePL/purduepl.github.io#192]
Context:
Today Ben pitched to people the idea of adding themselves to the website. Also, suggesting news, etc.

Problem:
It's easy enough to find the website, but it's a little annoying to get from the website to GitHub.

Proposal:
Could we have a link to the GitHub repo on the website somewhere?

**Comment by Pat-Lafon** [comment]
Like are you thinking to have a link underneath the description? Or more of a button somewhere?

Do you have an example website that you like that has this feature?

**Comment by ulysses4ever** [comment]
(when I say "another button", I mean buttons like "News", "Seminars", etc.)

**Comment by Pat-Lafon** [comment]
Hmm, I've looked at one or two other websites and they seem to often be just "Github" with the associated link. Our buttons are a little more heavy weight but maybe that's fine? Or maybe we could convert the buttons into just links like https://uwplse.org/

**Comment by Pat-Lafon** [comment]
See https://github.com/PurduePL/purduepl.github.io/commit/57915acafa87b05305d798c17fd45d76e13dfab8

**Comment by ulysses4ever** [comment]
Looks good, thanks!
