### ISSUE TITLE
Issue templates on this repo are too restrictive

### ISSUE THREAD

**Issue by ulysses4ever** [PurduePL/purduepl.github.io#193]
When I try to create issue here, I get to a page listing three templates:

- Add PurPL member
- News Post
- Seminar Talk Info

Would it be possible to have something like "Suggest Improvement" or a similar more free-form template?

**Comment by Pat-Lafon** [comment]
Sure, I've added a new form

**Comment by ulysses4ever** [comment]
Thank you!
