### ISSUE TITLE
Consider protecting the main branch from direct updates

### ISSUE THREAD

**Issue by ulysses4ever** [PurduePL/purduepl.github.io#194]
Problem:
GitHub is annoying in that it doesn't allow you to subscribe to updates on a particular branch easily. So, I miss what's going on with the website when people just push to the main branch. And eventually, I start forgetting about the website itself. Even though I did opt-in to "watch" the repo. 

Proposal:
Would it be comfortable for people to protect the main branch from direct updates and therefore force people to go via pull requests? On top of being more transparent, it fosters the idea that branch protection is the way to go in the modern world. 

Disclaimer:
If this is too much of a hassle and will break the maintainer's workflow hard, please, don't bother and feel free to close this issue.

**Comment by Pat-Lafon** [comment]
Hmm, that is a little annoying on Github's end.

There should still be a decent amount of traffic that you get notifications from? Most of the work I do on this repo is in response to issues that are opened or dependabot pr's. I occasionally push things that are unrelated to an issue/pr/workflow but those are rare(fixing typos, moving people to the alumni section). Do you get notified when Ben opens a news issue?

Given that I'm the only one actively pushing to the repo, my only plan to move to a pr-based system would be if there is automation to automatically create a pr when an issue is created. This is a mechanical enough process that it should be doable, but I haven't gotten around to it.

**Comment by ulysses4ever** [comment]
I got you, thanks. 

Issues do produce notifications, yes. 

Creating a PR out of an issue sounds not trivial.
