### ISSUE TITLE
What is the current status of the PurPL website?

### ISSUE THREAD

**Issue by Pat-Lafon** [PurduePL/purduepl.github.io#62]
What is the workflow to make changes? What is the difference between this website and https://purpl.cs.purdue.edu/ ?

I think @raghav198 is supposedly involved in this? Maybe @rcdickerson or @vixrant have input?

**Comment by vixrant** [comment]
Workflow I followed was to send in PRs https://github.com/PurduePL/purduepl.github.io/pulls?q=is%3Apr+is%3Aclosed

**Comment by rcdickerson** [comment]
Last semester I tried to get Vikrant commit access, but it seems nobody knows who actually has admin access to this GH account. The last I heard was Kia admined it, but he is no longer here, so... seems like a problem.

https://purpl.cs.purdue.edu is the "PurPL Center" which is (I guess?) somehow distinct from this PurPL. My impression was the Center page was more external-corporate-partner-facing, but I'm not sure what the difference is or if it still makes sense to have two separate sites.

**Comment by Pat-Lafon** [comment]
> Last semester I tried to get Vikrant commit access, but it seems nobody knows who actually has admin access to this GH account. The last I heard was maybe Kia admined it, but he is no longer here, so... seems like a problem.

I asked Kia and supposedly he set up the email access and gave it to Ben.

**Comment by Pat-Lafon** [comment]
Given that I've acquired commit access, I'm closing this issue as resolved.

**Comment by reikdas** [comment]
> https://purpl.cs.purdue.edu/ is the "PurPL Center" which is (I guess?) somehow distinct from this PurPL. My impression was the Center page was more external-corporate-partner-facing, but I'm not sure what the difference is or if it still makes sense to have two separate sites.

_Does_ it make sense to have two separate sites?

**Comment by Pat-Lafon** [comment]
Well you will have to ask Tiark about that since it's his website I believe. At the very least, I want to look into redirecting department links to this website if it's going to be more up to date with respect to what is going on and who the members of PurPL are (see #65).
