### ISSUE TITLE
Add member: Wenxin Jiang

### ISSUE THREAD

**Issue by Wenxin-Jiang** [PurduePL/purduepl.github.io#80]
### Name

Wenxin Jiang

### Current Status

Grad Student

### Optional website link

https://wenxin-jiang.github.io/

### Optional image

https://wenxin-jiang.github.io/images/profile_square.png

**Comment by Pat-Lafon** [comment]
Resolved by: bddd150efd6d7ec5a48bee05c56ee1756875b900
