### ISSUE TITLE
Seminar Talk: Juniper: a Functional Reactive Programming Language for the Arduino

### ISSUE THREAD

**Issue by calebh** [PurduePL/purduepl.github.io#94]
### Title

Juniper: a Functional Reactive Programming Language for the Arduino

### Abstract

For the past seven years I have been developing and maintaining Juniper, a domain specific language for programming Arduino devices. In this talk I will introduce the core features of the language, primarily how Juniper implements the functional reactive programming paradigm as well as a brief retrospective on the previous years of development.

### Bio

Caleb Helbling is a graduate student at Purdue University specializing in the area of programming languages. Before joining Purdue he was a VR developer at a small startup and an Assistant Staff member at MIT Lincoln Laboratory. At MIT Lincoln Laboratory he primarily focused on embedded system development, domain specific languages and graph theory research.

**Comment by Pat-Lafon** [comment]
Thanks! Resolved
