### ISSUE TITLE
Seminar Talk: Coyote: A Compiler for Vectorizing Encrypted Arithmetic Circuits

### ISSUE THREAD

**Issue by raghav198** [PurduePL/purduepl.github.io#98]
### Title
Coyote: A Compiler for Vectorizing Encrypted Arithmetic Circuits
### Abstract
Fully Homomorphic Encryption (FHE) is a scheme that allows a computational circuit to operate on encrypted data and produce a result that, when decrypted, yields the result of the unencrypted computation. While FHE enables privacy-preserving computation, it is extremely slow. However, the mathematical formulation of FHE supports a SIMD-like execution style, and hence recent work has turned to vectorization to recover some of the missing performance. Unfortunately, these vectorization approaches do not work well for arbitrary computations: they do not account for the high cost of rotating vector operands to allow data to be used in multiple operations. Hence, the cost of rotation can outweigh the benefits of vectorization. This paper presents Coyote, a new approach to vectorizing encrypted circuits that specifically aims to optimize the use of rotations. It tackles the scheduling and data layout problems simultaneously, operating at the level of subcircuits that can be vectorized without incurring excessive data movement overhead. By jointly searching for good vectorization and lane placement, Coyote finds schedules that avoid over-packing, or sacrificing one for the other. This paper shows that Coyote is effective at vectorizing computational kernels while minimizing rotations, thus finding efficient vector schedules and smart rotation schemes to achieve substantial speedups.

### Bio
Raghav Malik is a fourth-year PhD student at Purdue University advised by Milind Kulkarni. He's interested in developing compiler optimizations for programs that use Fully Homomorphic Encryption (FHE).

**Comment by Pat-Lafon** [comment]
Resolved
